services:
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app/backend/

  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app/frontend/
    environment:
      - NODE_ENV=development
